// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaazfhxpzzwnppgcvmbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhYXpmaHhwenp3bnBwZ2N2bWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwNTA3MzMsImV4cCI6MjA1MjYyNjczM30.zE3ST26s2XBjhk6kEkEpx93c-MzIQM1gPTGFTf4x-qE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);